### ISSUE TITLE
R 3.6.2 compatable

### ISSUE THREAD

**Issue by landLogic** [RobertMyles/tidygeoRSS#1]
Hi three, 
I am new to R and github. Is tidygeoRSS going to be available for R 3.6.2? 
I can't seem to find that info. 
I'm trying to pull Common Alerting Protocol public safety messages from a Canadian alert feed.
For some reason my network blocks the RSS but not the geoRSS. Go figure. 

I look forward to trying it out with tidygeoRSS 
Thanks

**Comment by RobertMyles** [comment]
Hi @landLogic,
Thanks for your interest in tidygeoRSS :-) 

However, it's still a work in progress. I'm hoping to have it finished in the next three weeks, or before if I'm able. At that point you'll be able to use it. I'll let you know here when it's at that point.

**Comment by RobertMyles** [comment]
Hi @landLogic,

tidygeoRSS should be in a suitable state for usage now. It is not yet on CRAN, so you can install it by using the remotes package: `remotes::install_github("RobertMyles/tidygeoRSS")`. Note that it relies for the moment on development versions of a few other packages, notably dplyr, rlang and tidyRSS, and you may have to install these in turn. What is the feed you're trying to parse? If you'd like to share it here, I can see if it works successfully.
